"""new fields in user model

Revision ID: 786f9c376ffb
Revises: c5ba92cf5532
Create Date: 2018-01-21 10:59:07.038015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786f9c376ffb'
down_revision = 'c5ba92cf5532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
